// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AccordionItem from "./islands/AccordionItem.tsx";
import * as $ButtonMenuInstitucionalMobile from "./islands/ButtonMenuInstitucionalMobile.tsx";
import * as $Popup from "./islands/Popup.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AccordionItem.tsx": $AccordionItem,
    "./islands/ButtonMenuInstitucionalMobile.tsx":
      $ButtonMenuInstitucionalMobile,
    "./islands/Popup.tsx": $Popup,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
